### OASIS INFOBYTE

### DATA SCIENCE

### TASK 4 EMAIL SPAM DETECTION WITH MACHINE LEARNING

In [86]:
import pandas as pd

In [87]:
df=pd.read_csv("smsspamcollection/SMSSpamCollection",sep='\t',names=['cat','text'])

In [88]:
df.head()

cat                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [89]:
len(df)

5572

In [90]:
import re

from nltk.corpus import stopwords

from nltk.stem import WordNetLemmatizer
wlemma=WordNetLemmatizer()

In [91]:
procsent=[]
for i in range(len(df)):
    words = re.sub('[^a-zA-Z]',' ',df['text'][i])
    words=words.lower()
    words=words.split()
    words=[wlemma.lemmatize(word) for word in words if word not in stopwords.words("english")]
    words=' '.join(words)
    procsent.append(words)

In [92]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [93]:
x=cv.fit_transform(procsent).toarray()

In [94]:
len(x)

5572

In [95]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [96]:
y=cv.fit_transform(df['cat'][:]).toarray()

In [97]:
y

array([[1, 0],
       [1, 0],
       [0, 1],
       ...,
       [1, 0],
       [1, 0],
       [1, 0]], dtype=int64)

In [98]:
df

cat                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [100]:
df

cat                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [102]:
df['cat']=df['cat'].replace('ham',0)
df['cat']=df['cat'].replace('spam',1)

In [105]:
y=df['cat']

### x and y data

In [106]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: cat, Length: 5572, dtype: int64

In [107]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [116]:
# data splitting

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=3,train_size=0.7)


In [117]:
len(x_train)

3900

In [119]:
len(x_test)

len(x_train)+len(x_test)

5572

In [131]:
from sklearn.naive_bayes import MultinomialNB
mnmodel=MultinomialNB()

mnmodel.fit(x_train,y_train)


y_pred=mnmodel.predict(x_test)



In [121]:
from sklearn.metrics import accuracy_score

In [124]:
mnmodel.score(x_test,y_test)*100

97.188995215311

In [129]:
from sklearn.metrics import confusion_matrix

In [133]:
confusion_matrix(y_test,y_pred)

array([[1404,   36],
       [  11,  221]], dtype=int64)

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   cat     5572 non-null   int64 
 1   text    5572 non-null   object
dtypes: int64(1), object(1)
memory usage: 87.2+ KB


In [138]:
df.isnull().any()

cat     False
text    False
dtype: bool

In [143]:
df['text'].unique()

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [153]:
df['cat'].value_counts()

0    4825
1     747
Name: cat, dtype: int64

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [159]:
y_test.value_counts()

0    1440
1     232
Name: cat, dtype: int64